/*
 * Paula Escobar is a terminal music player for demoscene and chip music.
 * Copyright © 2026 Adam Waldenberg, Adeptum AB, Org.nr 559494-1824.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * Website: https://www.adeptum.se
 * Contact: info@adeptum.se
 */

/**
 * ASAP, Another Slight Atari Player, copyright © 2005-2026 Piotr Fusik, https://asap.sourceforge.net, licensed
 * under the GNU General Public License version 2 or, at your option, any later version, and used here under
 * version 3. Every other file in this package is generated by fut 3.3.7 from ASAP's Fusion sources at commit
 * 9d01a358ad2725680fd8b8ea78f7a65870fafece; the 6502 players it loads are the binaries of release 8.0.0, kept
 * as resources beside it. tools/generate-asap produces all of it again, and nothing here is edited by hand.
 */
package net.sf.asap;
